/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/data/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 提交数据准备作业(异步;立即返回 job,不阻塞) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PrepareJobRequest"];
                };
            };
            responses: {
                /** @description accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                /** @description unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/data/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列本企业/组作业(必经 can() 按企业/组过滤;分页) */
        get: {
            parameters: {
                query?: {
                    status?: "queued" | "running" | "succeeded" | "failed";
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description jobs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobList"];
                    };
                };
                /** @description unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/data/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    job_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description job */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                /** @description forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/data/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列本企业/组原始数据集(必经 can() 过滤;分页) */
        get: {
            parameters: {
                query?: {
                    status?: "pending" | "ready" | "failed";
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RawDatasetList"];
                    };
                };
                /** @description unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** 请求上传原始数据(can() 过 → 服务端拼 key → 返回 presigned 直传 URL;ADR-020) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RawUploadRequest"];
                };
            };
            responses: {
                /** @description grant */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadGrant"];
                    };
                };
                /** @description invalid dataset/filename */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/data/raw/{raw_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 完成上传(入参仅 path id;服务端按记录再 can() + 校验对象;ADR-020 C-2) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    raw_id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CompleteUploadRequest"];
                };
            };
            responses: {
                /** @description rawdataset */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RawDataset"];
                    };
                };
                /** @description forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description object missing / complete failed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PrepareJobRequest: {
            dataset: string;
            group_id: string;
            source_dataset: string;
            np?: number | null;
            process?: Record<string, never>[] | null;
        };
        Job: {
            id: string;
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed";
            terminal: boolean;
            dataset: string;
            group_id: string;
            enterprise_id: string;
            source_dataset?: string | null;
            rows_in?: number | null;
            rows_written?: number | null;
            lance_uri?: string | null;
            error?: string | null;
            created_at?: string | null;
            updated_at?: string | null;
        };
        JobList: {
            jobs: components["schemas"]["Job"][];
            total: number;
        };
        RawUploadRequest: {
            dataset: string;
            group_id: string;
            filename: string;
            /** @default false */
            multipart: boolean;
            parts?: number | null;
        };
        UploadGrant: {
            raw_id: string;
            oss_key: string;
            url?: string | null;
            upload_id?: string | null;
            part_urls?: string[] | null;
            expires_in: number;
        };
        CompletePart: {
            part_number: number;
            etag: string;
        };
        CompleteUploadRequest: {
            parts?: components["schemas"]["CompletePart"][] | null;
        };
        RawDataset: {
            id: string;
            name: string;
            group_id: string;
            enterprise_id: string;
            oss_key: string;
            /** @enum {string} */
            status: "pending" | "ready" | "failed";
            size?: number | null;
            error?: string | null;
            created_at?: string | null;
            updated_at?: string | null;
        };
        RawDatasetList: {
            raw: components["schemas"]["RawDataset"][];
            total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
