/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/catalogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出本企业(token 推导)的 catalog */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description catalogs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NameList"];
                    };
                };
                /** @description unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalogs/{catalog}/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    catalog: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description schemas */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NameList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalogs/{catalog}/schemas/{schema}/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catalog: string;
                schema: string;
            };
            cookie?: never;
        };
        /** 列出数据集(can() 按 group 过滤) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    catalog: string;
                    schema: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description datasets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DatasetList"];
                    };
                };
            };
        };
        put?: never;
        /** 注册数据集 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    catalog: string;
                    schema: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterDataset"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dataset"];
                    };
                };
                /** @description forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description dataset already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalogs/{catalog}/schemas/{schema}/datasets/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    catalog: string;
                    schema: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description dataset */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dataset"];
                    };
                };
                /** @description forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NameList: {
            names?: string[];
        };
        Dataset: {
            name: string;
            enterprise_id: string;
            group_id: string;
            owner?: string | null;
            /** @enum {string} */
            scope: "private" | "shared";
            location: string;
            comment?: string | null;
            created_at?: string | null;
            created_by?: string | null;
            format?: string | null;
            num_samples?: number | null;
            size_bytes?: number | null;
        };
        DatasetList: {
            datasets?: components["schemas"]["Dataset"][];
        };
        RegisterDataset: {
            name: string;
            group_id: string;
            location: string;
            /**
             * @default private
             * @enum {string}
             */
            scope: "private" | "shared";
            comment?: string | null;
            format?: string | null;
            num_samples?: number | null;
            size_bytes?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
