# generated by datamodel-codegen:
#   filename:  data-pipeline.yaml

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, conint, constr


class PrepareJobRequest(BaseModel):
    dataset: constr(pattern=r'^[a-z0-9][a-z0-9_-]{0,63}$')
    group_id: constr(pattern=r'^g-[0-9a-z]+$')
    tar_dir: str
    np: conint(ge=1) | None = None
    process: list[dict[str, Any]] | None = None


class Status(Enum):
    queued = 'queued'
    running = 'running'
    succeeded = 'succeeded'
    failed = 'failed'


class Job(BaseModel):
    id: str
    status: Status
    terminal: bool
    dataset: str
    group_id: constr(pattern=r'^g-[0-9a-z]+$')
    enterprise_id: constr(pattern=r'^e-[0-9a-z]+$')
    rows_in: int | None = None
    rows_written: int | None = None
    lance_uri: str | None = None
    error: str | None = None
    created_at: str | None = None
    updated_at: str | None = None


class JobList(BaseModel):
    jobs: list[Job]
    total: int
