# generated by datamodel-codegen:
#   filename:  identity-org.yaml

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, constr


class Role(Enum):
    member = 'member'
    enterprise_admin = 'enterprise-admin'


class Membership(BaseModel):
    enterprise_id: constr(pattern=r'^[a-z][a-z0-9-]{3,}$')
    role: Role


class Enterprise(BaseModel):
    alias: constr(pattern=r'^[a-z][a-z0-9-]{3,}$')
    display_name: str | None = None


class Memberships(BaseModel):
    user: str | None = None
    is_platform_admin: bool | None = None
    memberships: list[Membership] | None = None
    enterprises: list[Enterprise] | None = None
