# generated by datamodel-codegen:
#   filename:  identity-org.yaml

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, constr


class Role(Enum):
    member = 'member'
    group_admin = 'group-admin'
    enterprise_admin = 'enterprise-admin'


class Membership(BaseModel):
    enterprise_id: constr(pattern=r'^e-[0-9a-z]+$')
    group_id: constr(pattern=r'^g-[0-9a-z]+$') | None = None
    role: Role


class Memberships(BaseModel):
    user: str | None = None
    is_platform_admin: bool | None = None
    memberships: list[Membership] | None = None
