# generated by datamodel-codegen:
#   filename:  metadata.yaml

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, conint, constr


class NameList(BaseModel):
    names: list[str] | None = None


class Scope(Enum):
    private = 'private'
    shared = 'shared'


class Dataset(BaseModel):
    name: str
    enterprise_id: constr(pattern=r'^e-[0-9a-z]+$')
    group_id: constr(pattern=r'^g-[0-9a-z]+$')
    owner: str | None = None
    scope: Scope
    location: str
    comment: str | None = None
    created_at: str | None = None
    created_by: str | None = None
    format: str | None = None
    num_samples: int | None = None
    size_bytes: int | None = None


class DatasetList(BaseModel):
    datasets: list[Dataset] | None = None


class RegisterDataset(BaseModel):
    name: constr(pattern=r'^[a-z0-9][a-z0-9_-]{0,63}$')
    group_id: constr(pattern=r'^g-[0-9a-z]+$')
    location: str
    scope: Scope | None = 'private'
    comment: str | None = None
    format: str | None = None
    num_samples: conint(ge=0) | None = None
    size_bytes: conint(ge=0) | None = None
