# generated by datamodel-codegen:
#   filename:  metadata.yaml

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, conint, constr


class NameList(BaseModel):
    names: list[str] | None = None


class Scope(Enum):
    private = 'private'
    shared = 'shared'


class Dataset(BaseModel):
    name: str
    enterprise_id: constr(pattern=r'^[a-z][a-z0-9-]{3,}$')
    owner: str | None
    scope: Scope
    location: str
    comment: str | None = None
    created_at: str | None = None
    created_by: str | None = None
    format: str | None = None
    num_samples: int | None = None
    size_bytes: int | None = None
    kind: str | None = None
    derived_from: str | None = None


class DatasetList(BaseModel):
    datasets: list[Dataset] | None = None


class Kind(Enum):
    raw = 'raw'
    processed = 'processed'


class RegisterDataset(BaseModel):
    name: constr(pattern=r'^[a-z0-9][a-z0-9_-]{0,63}$')
    kind: Kind
    location: str | None = None
    derived_from: str | None = None
    scope: Scope | None = 'private'
    comment: str | None = None
    format: str | None = None
    num_samples: conint(ge=0) | None = None
    size_bytes: conint(ge=0) | None = None
